name: Calculator CI Workflow

on:
  push:
    branches:
      - main

jobs:
  test-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Linting
        run: flake8 . --ignore=W292,W293

      - name: Run Unit Tests
        run: python -m unittest test_calculator.py -v